name: Update README.md Automatically

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  update-readme:
    if: >
      github.event_name == 'push' ||
      (github.event.pull_request.merged == true && github.event.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt 파일이 없습니다."
          fi

      - name: README.md 생성
        run: python scripts/generate_readme.py

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'chore: auto-update README.md' || echo "변경 사항 없음"
          git push origin HEAD:main || echo "푸시 실패"